### ISSUE TITLE
Add support for DELETE requests

### ISSUE THREAD

**Issue by johan-bjareholt** [spietika/restson-rust#1]
Have been using this library now for a few hours and seems to work very well and the implementation is simple so it's a joy to use. The examples were very useful!

I do need to do a DELETE request however and that does not seem to be implemented.

I am very new to Rust but it should be rather simple to implement.
I just wanted to tell you that if you do not intend implement this yourself soon, I might in a few weeks when I get more time.

**Comment by spietika** [comment]
Thanks for your feedback, and sorry for the long delay to reply! As you said implementing DELETE should be pretty straightforward. I should have time this weekend to implement it.

**Comment by spietika** [comment]
I was thinking about the DELETE request. At the moment GET and POST have different variants. I haven't seen DELETE used much in REST API's so I'm not sure which variants should be supported: request body, capture response body, request parameters? Or is it enough to simply to have DELETE to specific API path without body and request parameters?

**Comment by johan-bjareholt** [comment]
As far as I know it's rare with having a body in a DELETE request (and I personally have no use for it), but it exists I believe. Some googling seemed to confirm this https://stackoverflow.com/questions/299628/is-an-entity-body-allowed-for-an-http-delete-request

**Comment by spietika** [comment]
It is also my understanding that DELETE request with body is pretty rare. So, I decided to only implement delete without body and without capturing the server response body. If needed, those can be added in future.

The DELETE support is now available in master. I'm planning to do some additional minor improvements so I did not push new version to crates.io yet.

**Comment by johan-bjareholt** [comment]
Nice! Fetched it from master and tested it out, works well!
All my usecases are fullfilled now it seems, thanks for the help! :)

Here's my rest client, likely lots of implementation faults as I'm new to rust but it works:
https://github.com/activitywatch/aw-client-rust

**Comment by StarlessNights** [comment]
I have been using restson with [Snipe-IT](https://github.com/snipe/snipe-it)'s API without any issues up until now (so thanks for that!).

However now I've come to realize that this API would need a `delete_capture` method. They have [a philosophy of always returning 200 unless the server itself fails.](https://snipe-it.readme.io/reference/api-overview#philosophy)

So without capture there's no way of telling whether it actually worked.

I have no idea how common practice this is.

**Comment by spietika** [comment]
Hi @StarlessNights !

I originally left `delete_capture` out since I thought that it would be very uncommon to have response body in DELETE requests. Though, adding that interface is a straighforward task so I now added both `delete_capture` and `delete_capture_with`. I just published these changes to v1.5.0 in crates.io.
