### ISSUE TITLE
Allow getting non-json body response?

### ISSUE THREAD

**Issue by nbigaouette-eai** [spietika/restson-rust#11]
I need to POST to a weird API where the response body is not json (but XML 😢).

Because of this I cannot use [`post_capture()`](https://github.com/spietika/restson-rust/blob/master/src/lib.rs#L329-L333) since it explicitly uses [`serde_json::from_str(body.as_str())`](https://github.com/spietika/restson-rust/blob/master/src/lib.rs#L349).

Could it be possible to get access to the (`String`) body directly? Or maybe have the possibility to pass a different function to deserialize the data?

Thanks!!

**Comment by nbigaouette-eai** [comment]
A workaround would be to return the actual body string when deserialization to json fails. For example:

```diff
diff --git a/src/lib.rs b/src/lib.rs
index c264c85..f7cf91f 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -93,9 +92,11 @@ pub enum Error {
     /// Failed to parse final URL.
     UrlError,

-    /// Failed to deserialize data to struct (in GET) or failed to
-    /// serialize struct to JSON (in POST).
-    ParseError(serde_json::Error),
+    /// Failed serialize struct to JSON (in POST).
+    SerializeParseError(serde_json::Error),
+
+    /// Failed to deserialize data to struct (in GET).
+    DeserializeParseError(serde_json::Error, String),

     /// Failed to make the outgoing request.
     RequestError,
```

and change all the `serde_json::from_str(body.as_str()).map_err(Error::ParseError)` to `serde_json::from_str(body.as_str()).map_err(|err| Error::DeserializeParseError(err, body))`.

This way I can then deserialize the string any way I like (or not at all).

**Comment by spietika** [comment]
I can see that this workaround is also useful in a general sense (e.g. debugging the returned body on error).

Supporting other serializers besides JSON is something that I have thought of. Though, JSON is so common that personally I have not needed other serialize options. It would be a good future enhancement.
