### ISSUE TITLE
Format code base using `rustfmt` for easier contribution

### ISSUE THREAD

**Issue by nbigaouette-eai** [spietika/restson-rust#13]
While working on a PR, my editor formatted the whole file `lib.rs` and I had to redo the edits by disabling autoformat.

rustfmt is now stable with 1.31: `rustfmt 1.0.0-stable (4a4e5081 2018-11-29)`.

**Comment by spietika** [comment]
Thanks for taking the time to make the PR even though you had to redo it! Appreciate it. I will run the project through rustfmt.
