### ISSUE TITLE
Compilation issue with serde_derive

### ISSUE THREAD

**Issue by nbigaouette-eai** [spietika/restson-rust#14]
I'd like to expose my client to Python so I'm trying to use [milksnake](https://github.com/getsentry/milksnake) to do so.

There seems to [be a problem](https://github.com/eqrion/cbindgen/issues/203) with cbindgen (used inside milksnake) which [requires a fixed version of serde_derive (1.0.58)](https://github.com/eqrion/cbindgen/blob/44e9b2112a06e46ddda6073e237d3a56df39c3e2/Cargo.toml#L24-L27).

But since [restson explictly requires `^1.0.80`](https://github.com/spietika/restson-rust/blob/1007041c511ef9c6d46bebc45182dd7525889139/Cargo.toml#L19), the combination of both cannot be used.

Could it be possible to relax the exact dependencies, at least for `serde_derive`? I think getting rid of the patch values should be enough:
```
hyper = "^0.12"
hyper-tls = "^0.3"
futures = "^0.1"
tokio-core = "^0.1"
serde = "^1.0"
serde_json = "^1.0"
serde_derive = "^1.0"
url = "^1.7"
log = "^0.4"
base64 = "^0.10"
```
letting cargo pick up the latest version. No need for a "required minimal patch version". And I believe this is the same as:
```
hyper = "0.12"
hyper-tls = "0.3"
futures = "0.1"
tokio-core = "0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
url = "1.7"
log = "0.4"
base64 = "0.10"
```

**Comment by nbigaouette-eai** [comment]
Hum... I screwed up and opened a PR to my own fork... 🤔 
See https://github.com/nbigaouette-eai/restson-rust/pull/1

**Comment by spietika** [comment]
I also relaxed the version for serde and serde_json. Many other dependencies have not reached 1.0 yet, so I'll probably keep the minimum patch version just in case, unless similar problems arise.
