### ISSUE TITLE
Add support for lists as the root object

### ISSUE THREAD

**Issue by johan-bjareholt** [spietika/restson-rust#2]
When doing requests, doing requests which expects the format of a object with a key which contains a list works fine, example:

```
{
    "mylist": ["a", "b", "c"]
}
```

I cannot however do a requests which expects a list as the root object due to how serde works, example:

```
["a", "b", "c"]
```

**Comment by robsaunders** [comment]
wish I'd seen this before I played with this lib :D

**Comment by spietika** [comment]
Thanks for pointing this out. The library depends fully on serde for (de)serialization. I'll take a look if there's a way to handle this in serde or if this could be handled in Restson.

**Comment by spietika** [comment]
I did a quick test and it is already possible to use APIs that return array root element. Here's an example:
`#[macro_use]
extern crate serde_derive;
extern crate serde;

extern crate restson;
use restson::{RestClient,RestPath,Error};

#[derive(Deserialize,Serialize,Debug)]
#[serde(untagged)]
enum MyData {
    Array(Vec<String>)
}

impl RestPath<()> for MyData {
    fn get_path(_: ()) -> Result<String,Error> { Ok(String::from("array")) }
}

fn main() {
    let mut client = RestClient::new("http://localhost:8080").unwrap();
    let data: MyData = client.get(()).unwrap();

    println!("{:?}", data);
}`

Hopefully this helps. I'll add an example to readme with some explanation also.

**Comment by johan-bjareholt** [comment]
Thanks a lot, got it working and works well!

I guess serde became a bit overwhelming when you're completely new to rust :)

**Comment by robsaunders** [comment]
I also worked this out - I wanted to come back and leave the solution but I'd forgotten the link! Thank you :)
