### ISSUE TITLE
expose response headers on successful request/response

### ISSUE THREAD

**Issue by grenade** [spietika/restson-rust#21]
perhaps this is implemented and just needs documenting but i'm struggling to understand how to retrieve response headers when a request is successful.

the github api v3 paginates responses and populates the link header with information including the page number of the last available page (see: https://developer.github.com/v3/guides/traversing-with-pagination).

it's necessary to parse the response headers to understand what pages are available.

is there a way to access the response headers within the existing implementation?

**Comment by spietika** [comment]
Firstly, sorry it took so long to reply to you. I have not been active with this project in past months.

As you have probably notices, the current implementation does not capture the received headers for requests. I will add a new function to the public interface were they can be accessed.
