### ISSUE TITLE
Documentation: Use newtype for JSON with array root element

### ISSUE THREAD

**Issue by jglauche** [spietika/restson-rust#24]
Following the documentation in the section "JSON with array root element", I ended up with a lot of overhead having to deal with the enum having an array with one Vec element. Using a newtype struct seems to be a much easier way to deal with this, example:

```
#[derive(Serialize,Deserialize,Debug,Clone)]
struct Products ( pub Vec<Product> );

#[derive(Serialize,Deserialize,Debug,Clone)]
pub struct Product {
    pub name: String,
    [....]
}

impl RestPath<()> for Products { fn get_path(_: ()) -> Result<String,Error> { Ok(String::from("/api/objects/products"))}}

pub fn products(&self) -> Vec<Product> {  
    let mut client = RestClient::new("http://localhost:8080").unwrap();
    client.get::<_, Products>(()).unwrap().0 
}
```
This makes it much easier and cleaner to expose the actual contents of Product. I tried the suggested solution with enum before and had a hard time getting the actual contents having to deal with different enums types.

**Comment by spietika** [comment]
Thanks for the suggestion! I updated the readme with your example code.
