### ISSUE TITLE
Response Body HttpError

### ISSUE THREAD

**Issue by robbym** [spietika/restson-rust#3]
Is there a way to get the response body when the server returns something other than 200 OK?

**Comment by robbym** [comment]
Maybe have HttpError(u16, String)?

**Comment by spietika** [comment]
This is a good idea. It would be nice if the error body would also be deserialized. Though, all APIs might not return JSON in error situation so it's probably safer to just use the plain String. It would also add another template parameter to requests, so the simple String approach is probably better here.

So in that regard the PR seems ok. Would you mind to add a simple test case for this (e.g. using https://httpbin.org/status/ API)? Alternatively I can accept as is, and add it myself.

Thanks for the contribution!
