### ISSUE TITLE
How should restson-rust users disable check ssl certification?

### ISSUE THREAD

**Issue by saidvandeklundert** [spietika/restson-rust#31]
I love using this package. 

Main issue I have moving forward with it is that in our staging environment, several services do not have a valid ssl cert.

How should I disable the ssl certification check when using restson?

```
HyperError(hyper::Error(Connect, Os { code: -2146762487, kind: Other, message: "A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider." }))
```

For testing, I would like to disable this check.

**Comment by spietika** [comment]
I have not tried this case, but I think it should be possible by using the Builder and providing your own HyperClient that is configured to disable cert verification.

Probably something along these lines until step 3. https://www.rusoto.org/disable-ssl-cert-check.html

And then once you have the HttpsConnector, you should be able to construct the Hyper client like here: https://github.com/spietika/restson-rust/blob/93b56efce463478805af5109a21de454b6fe827a/src/lib.rs#L252

As said, I have not tried this in practice. I'll try to see if I have time in the coming days to write a proper code example. Hope this helps!

**Comment by spietika** [comment]
Closing as an old stale issue.
