### ISSUE TITLE
Allow for using rustls instead of native-tls

### ISSUE THREAD

**Issue by xfbs** [spietika/restson-rust#34]
Should restson maybe have parameters to allow for using rustls?

**Comment by spietika** [comment]
Hyper supports rustls so it should not be a big effort to add the support here, and I think such option parameter would make sense.

For now, it should already be possible (I haven't tested this) to use rustls by constructing your own Hyper client and using the `with_client()` in the builder: https://github.com/spietika/restson-rust/blob/master/src/lib.rs#L210

Though this is not very convenient so having it as an option would make sense.

**Comment by spietika** [comment]
This is now (finally) possible in version 1.4.0 by using `rustls` feature.
